DECLARE @START int
SET @START = 65
While(@START <= 90)
Begin
	PRINT CHAR(@START)
	SET @START = @START + 1

END

--PRINT COUNTING 0 TO 10000
DECLARE @START int
SET @START = 0
While(@START <= 100000)
Begin
	PRINT @START
	SET @START = @START + 1

END

-- REVERSE THE STRING
PRINT(REVERSE('LEARNING SQL OBJECT'))
